/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicios;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author marta
 */
public class Ejercicio5 extends javax.swing.JFrame {

    private Timer tiempo;
    int horas, minutos, segundos, centesimas;
    /**
     * Creates new form Ejercicio5
     */
    public Ejercicio5() {
        initComponents();
        aniadirImagen();
        horas=0;
        minutos=0;
        segundos=0;
        centesimas=0;
        
        ActionListener acciones = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                centesimas+=1;
                if (centesimas==100) {
                    segundos+=1;
                    centesimas=0;
                }
                if (segundos==60){
                    minutos+=1;
                    segundos=0;
                }
                if (minutos==60) {
                    horas+=1;
                    minutos=0;
                }
                actualizarEtiquetaTiempo();
            }
            
        };
        
        tiempo = new Timer(10, acciones);
        
        botonIniciar();
        botonPausar();
        botonDetener();
    }
    
    private void actualizarEtiquetaTiempo() {
        String hora, minuto, segundo, centesima;
        
        if (horas<=9) {
            hora="0" + Integer.toString(horas);
        }
        else {
            hora = Integer.toString(horas);
        }
        
        if (minutos<=9) {
            minuto="0" + Integer.toString(minutos);
        }
        else {
            minuto = Integer.toString(minutos);
        }
        
        if (segundos<=9) {
            segundo="0" + Integer.toString(segundos);
        }
        else {
            segundo = Integer.toString(segundos);
        }
        
        if (centesimas<=9) {
            centesima="0" + Integer.toString(centesimas);
        }
        else {
            centesima = Integer.toString(centesimas);
        }
        
        String tiempo_str = hora+":"+minuto+":"+segundo+":"+centesima;
        etiqueta_tiempo.setText(tiempo_str);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        etiqueta_cronometro = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        etiqueta_tiempo = new javax.swing.JLabel();
        boton_iniciar = new javax.swing.JButton();
        boton_pausar = new javax.swing.JButton();
        boton_detener = new javax.swing.JButton();
        etiqueta_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(etiqueta_cronometro, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 150, 150));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Cronómetro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 210, 40));

        etiqueta_tiempo.setBackground(new java.awt.Color(255, 255, 255));
        etiqueta_tiempo.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        etiqueta_tiempo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etiqueta_tiempo.setText("00:00:00:00");
        etiqueta_tiempo.setOpaque(true);
        jPanel1.add(etiqueta_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(321, 111, 180, 50));

        boton_iniciar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_iniciar.setText("Iniciar");
        jPanel1.add(boton_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 90, 40));

        boton_pausar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_pausar.setText("Pausar");
        jPanel1.add(boton_pausar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 210, 90, 40));

        boton_detener.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton_detener.setText("Detener");
        jPanel1.add(boton_detener, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 100, 40));

        etiqueta_fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\marta.PILSA\\OneDrive - Construcciones Pilsa SL\\Documentos\\NetBeansProjects\\interfacesgraficas\\images\\carrera1.jpg")); // NOI18N
        jPanel1.add(etiqueta_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void aniadirImagen() {
        ImageIcon image = new ImageIcon("./images/cronometro.png");
        ImageIcon image_scalated = new ImageIcon(image.getImage().
                getScaledInstance(etiqueta_cronometro.getWidth(), etiqueta_cronometro.getHeight(), Image.SCALE_SMOOTH)); //Escalar una imagen
        
        etiqueta_cronometro.setIcon(image_scalated);
    }
    
    private void botonIniciar() {
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tiempo.start();
            }
        };
        boton_iniciar.addActionListener(listener);
    }
    private void botonPausar() {
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tiempo.stop();
            }
        };
        boton_pausar.addActionListener(listener);
    }
    
    private void botonDetener() {
        ActionListener listener = new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tiempo.stop();
                horas = 0;
                minutos = 0;
                segundos = 0;
                centesimas = 0;
                etiqueta_tiempo.setText("00:00:00:00");
            }
        };
        boton_detener.addActionListener(listener);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton_detener;
    private javax.swing.JButton boton_iniciar;
    private javax.swing.JButton boton_pausar;
    private javax.swing.JLabel etiqueta_cronometro;
    private javax.swing.JLabel etiqueta_fondo;
    private javax.swing.JLabel etiqueta_tiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
