/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicios.Ejercicio9;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author marta
 */
public class VentanaJuego extends javax.swing.JFrame {

    private boolean turno;
    private boolean posiciones[][];
    private int pulsados[][];
    private int ganador;
    String usuario1, usuario2;
    int contador;
    
    public VentanaJuego() {
        
        
    }
    
    public VentanaJuego(String usuario1, String usuario2) {
        turno = false;
        posiciones = new boolean[3][3];
        pulsados = new int[3][3];
        ganador = 0;
        this.usuario1 = usuario1;
        this.usuario2 = usuario2;
        contador = 0;
        
        inicializarPosiciones();
        inicializarPulsados();
        initComponents();
        
    }
    
    private void inicializarPosiciones() {
        for (int i=0; i<3; i++) {
            for (int j=0; j<3; j++){
                posiciones[i][j] = false;
            }
        }
    }
    
    private void inicializarPulsados() {
        for (int i=0; i<3; i++) {
            for (int j=0; j<3; j++){
                pulsados[i][j] = 0;
            }
        }
    }
    
    private void dibujarX(JButton boton) {
        
        ImageIcon image = new ImageIcon("./images/x.png");
        boton.setIcon(image);
    }

    private void dibujarO(JButton boton) {
        ImageIcon image = new ImageIcon("./images/o.png");
        
        boton.setIcon(image);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        boton00 = new javax.swing.JButton();
        boton01 = new javax.swing.JButton();
        boton02 = new javax.swing.JButton();
        boton10 = new javax.swing.JButton();
        boton11 = new javax.swing.JButton();
        boton12 = new javax.swing.JButton();
        boton20 = new javax.swing.JButton();
        boton21 = new javax.swing.JButton();
        boton22 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(501, 501));

        jPanel1.setLayout(new java.awt.GridLayout(3, 0));

        boton00.setMaximumSize(new java.awt.Dimension(167, 167));
        boton00.setPreferredSize(new java.awt.Dimension(167, 167));
        boton00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton00ActionPerformed(evt);
            }
        });
        jPanel1.add(boton00);

        boton01.setMaximumSize(new java.awt.Dimension(167, 167));
        boton01.setPreferredSize(new java.awt.Dimension(167, 167));
        boton01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton01ActionPerformed(evt);
            }
        });
        jPanel1.add(boton01);

        boton02.setMaximumSize(new java.awt.Dimension(167, 167));
        boton02.setPreferredSize(new java.awt.Dimension(167, 167));
        boton02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton02ActionPerformed(evt);
            }
        });
        jPanel1.add(boton02);

        boton10.setMaximumSize(new java.awt.Dimension(167, 167));
        boton10.setPreferredSize(new java.awt.Dimension(167, 167));
        boton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton10ActionPerformed(evt);
            }
        });
        jPanel1.add(boton10);

        boton11.setMaximumSize(new java.awt.Dimension(167, 167));
        boton11.setPreferredSize(new java.awt.Dimension(167, 167));
        boton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton11ActionPerformed(evt);
            }
        });
        jPanel1.add(boton11);

        boton12.setMaximumSize(new java.awt.Dimension(167, 167));
        boton12.setPreferredSize(new java.awt.Dimension(167, 167));
        boton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton12ActionPerformed(evt);
            }
        });
        jPanel1.add(boton12);

        boton20.setMaximumSize(new java.awt.Dimension(167, 167));
        boton20.setPreferredSize(new java.awt.Dimension(167, 167));
        boton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton20ActionPerformed(evt);
            }
        });
        jPanel1.add(boton20);

        boton21.setMaximumSize(new java.awt.Dimension(167, 167));
        boton21.setPreferredSize(new java.awt.Dimension(167, 167));
        boton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton21ActionPerformed(evt);
            }
        });
        jPanel1.add(boton21);

        boton22.setMaximumSize(new java.awt.Dimension(167, 167));
        boton22.setPreferredSize(new java.awt.Dimension(167, 167));
        boton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton22ActionPerformed(evt);
            }
        });
        jPanel1.add(boton22);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton00ActionPerformed
        // TODO add your handling code here:
        if (!posiciones[0][0]){
            if (!turno){
                dibujarX(boton00);
                pulsados[0][0] = 1;
            }
            else{
                dibujarO(boton00);
                pulsados[0][0] = 2;
            }

            comprobarGanador();
            turno = !turno;
            
            
            if (ganador == 1 ){
                new VentanaGanar(this, false, usuario1).setVisible(true);
            }
            else if (ganador == 2) {
                new VentanaGanar(this, false, usuario2).setVisible(true);
            }
            
            contador++;
            
            if (contador == 9) {
                new VentanaEmpate(this, true).setVisible(true);
            }
        }
        
        posiciones[0][0] = true;
    }//GEN-LAST:event_boton00ActionPerformed

    private void boton01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton01ActionPerformed
        // TODO add your handling code here:
        if (!posiciones[0][1]){
            if (!turno){
                dibujarX(boton01);
                pulsados[0][1]=1;
            }
            else{
                dibujarO(boton01);
                pulsados[0][1] = 2;
            }

            comprobarGanador();
            turno = !turno;
            
            if (ganador == 1 ){
                new VentanaGanar(this, false, usuario1).setVisible(true);
            }
            else if (ganador == 2) {
                new VentanaGanar(this, false, usuario2).setVisible(true);
            }
            
            contador++;
            
            if (contador == 9) {
                new VentanaEmpate(this, true).setVisible(true);
            }
        }
        
        posiciones[0][1] = true;
    }//GEN-LAST:event_boton01ActionPerformed

    private void boton02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton02ActionPerformed
        // TODO add your handling code here:
        if (!posiciones[0][2]){
            if (!turno){
                dibujarX(boton02);
                pulsados[0][2] = 1;
            }
            else {
                dibujarO(boton02);
                pulsados[0][2] = 2;
            }

            comprobarGanador();
            turno = !turno;
            
            if (ganador == 1 ){
                new VentanaGanar(this, false, usuario1).setVisible(true);
            }
            else if (ganador == 2) {
                new VentanaGanar(this, false, usuario2).setVisible(true);
            }
            
            contador++;
            
            if (contador == 9) {
                new VentanaEmpate(this, true).setVisible(true);
            }
        }
        
        posiciones[0][2] = true;
    }//GEN-LAST:event_boton02ActionPerformed

    private void boton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton10ActionPerformed
        // TODO add your handling code here:
        if (!posiciones[1][0]){
            if (!turno){
                dibujarX(boton10);
                pulsados[1][0] = 1;
            }
            else{
                dibujarO(boton10);
                pulsados[1][0] = 2;
            }

            comprobarGanador();
            turno = !turno;
            
            if (ganador == 1 ){
                new VentanaGanar(this, false, usuario1).setVisible(true);
            }
            else if (ganador == 2) {
                new VentanaGanar(this, false, usuario2).setVisible(true);
            }
            
            contador++;
            
            if (contador == 9) {
                new VentanaEmpate(this, true).setVisible(true);
            }
        }
        
        posiciones[1][0] = true;
    }//GEN-LAST:event_boton10ActionPerformed

    private void boton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton11ActionPerformed
        // TODO add your handling code here:
        if (!posiciones[1][1]){
            
            
            if (!turno) {
                dibujarX(boton11);
                pulsados[1][1] = 1;
            }
            else {
                dibujarO(boton11);
                pulsados[1][1] = 2;
            }

            comprobarGanador();
            turno = !turno;
            
            if (ganador == 1 ){
                new VentanaGanar(this, false, usuario1).setVisible(true);
            }
            else if (ganador == 2) {
                new VentanaGanar(this, false, usuario2).setVisible(true);
            }
            
            contador++;
            
            if (contador == 9) {
                new VentanaEmpate(this, true).setVisible(true);
            }
        }
        
        posiciones[1][1] = true;
        
    }//GEN-LAST:event_boton11ActionPerformed

    private void boton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton12ActionPerformed
        // TODO add your handling code here:
        if (!posiciones[1][2]){
            
            
            if (!turno){
                dibujarX(boton12);
                pulsados[1][2] = 1;
            }
            else {
                dibujarO(boton12);
                pulsados[1][2] = 2;
            }

            comprobarGanador();
            turno = !turno;
            
            if (ganador == 1 ){
                new VentanaGanar(this, false, usuario1).setVisible(true);
            }
            else if (ganador == 2) {
                new VentanaGanar(this, false, usuario2).setVisible(true);
            }
            
            contador++;
            
            if (contador == 9) {
                new VentanaEmpate(this, true).setVisible(true);
            }
        }
        
        posiciones[1][2] = true;
    }//GEN-LAST:event_boton12ActionPerformed

    private void boton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton20ActionPerformed
        // TODO add your handling code here:
        if (!posiciones[2][0]){
            
            
            if (!turno) {
                dibujarX(boton20);
                pulsados[2][0] = 1;
            }
            else {
                dibujarO(boton20);
                pulsados[2][0] = 2;
            }

            comprobarGanador();
            turno = !turno;
            
            if (ganador == 1 ){
                new VentanaGanar(this, false, usuario1).setVisible(true);
            }
            else if (ganador == 2) {
                new VentanaGanar(this, false, usuario2).setVisible(true);
            }
            
            contador++;
            
            if (contador == 9) {
                new VentanaEmpate(this, true).setVisible(true);
            }
        }
        
        posiciones[2][0] = true;
    }//GEN-LAST:event_boton20ActionPerformed

    private void boton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton21ActionPerformed
        // TODO add your handling code here:
        if (!posiciones[2][1]){
            
            
            if (!turno) {
                dibujarX(boton21);
                pulsados[2][1] = 1;
            }
            else {
                dibujarO(boton21);
                pulsados[2][1] = 2;
            }

            comprobarGanador();
            turno = !turno;
            
            if (ganador == 1 ){
                new VentanaGanar(this, false, usuario1).setVisible(true);
            }
            else if (ganador == 2) {
                new VentanaGanar(this, false, usuario2).setVisible(true);
            }
            
            contador++;
            
            if (contador == 9) {
                new VentanaEmpate(this, true).setVisible(true);
            }
        }
        
        
        posiciones[2][1] = true;
    }//GEN-LAST:event_boton21ActionPerformed

    private void boton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton22ActionPerformed
        // TODO add your handling code here:
        if (!posiciones[2][2]){
                     
            
            if (!turno) {
                dibujarX(boton22);
                pulsados[2][2] = 1;
            }
            else{
                dibujarO(boton22);
                pulsados[2][2] = 2;
            }
            comprobarGanador();
            turno = !turno;
            
            
            
            if (ganador == 1 ){
                new VentanaGanar(this, false, usuario1).setVisible(true);
            }
            else if (ganador == 2) {
                new VentanaGanar(this, false, usuario2).setVisible(true);
            }
            
            contador++;
            
            if (contador == 9) {
                new VentanaEmpate(this, true).setVisible(true);
            }
            
            
            
        }
        
        posiciones[2][2] = true;
    }//GEN-LAST:event_boton22ActionPerformed

    private void comprobarGanador() {
        /*for (int i=0; i<3; i++) {
            for (int j=0; j<3; j++) {
                System.out.print(pulsados[i][j]);
            }
            System.out.println("");
        }*/
        if (!turno) { // Primer jugador
            if (pulsados[0][0] == 1){
                if ((pulsados[0][1]==1 && pulsados[0][2] == 1) || 
                        (pulsados[1][0]==1 && pulsados[2][0] == 1) ||
                        (pulsados[1][1]==1 && pulsados[2][2] == 1))
                {
                    ganador = 1;
                }
            }
            else if (pulsados[0][1] == 1) {
                if (pulsados[1][1] == 1 && pulsados[2][1] == 1) {
                    ganador = 1;
                }
            }
            else if (pulsados[0][2] == 1){
                if (pulsados[1][2] == 1 && pulsados[2][2]==1) {
                    ganador = 1;
                }
            }
            else if (pulsados[1][0] == 1) {
                if (pulsados[1][1] == 1 && pulsados[1][2] == 1) {
                    ganador = 1;
                }
            }
            else if (pulsados[2][0] == 1) {
                if (pulsados[2][1] == 1 && pulsados[2][2] == 1) {
                    ganador = 1;
                }
            }
        
        }
        else { // Segundo jugador
            if (pulsados[0][0] == 2){
                if ((pulsados[0][1]== 2 && pulsados[0][2] == 2) || 
                        (pulsados[1][0]== 2 && pulsados[2][0] == 2) ||
                        (pulsados[1][1]== 2 && pulsados[2][2] == 2))
                {
                    ganador = 2;
                }
            }
            else if (pulsados[0][1] == 2) {
                if (pulsados[1][1] == 2 && pulsados[2][1] == 2) {
                    ganador = 2;
                }
            }
            else if (pulsados[0][2] == 2){
                if (pulsados[1][2] == 2 && pulsados[2][2]== 2) {
                    ganador = 2;
                }
            }
            else if (pulsados[1][0] == 2) {
                if (pulsados[1][1] == 2 && pulsados[1][2] == 2) {
                    ganador = 2;
                }
            }
            else if (pulsados[2][0] == 2) {
                if (pulsados[2][1] == 2 && pulsados[2][2] == 2) {
                    ganador = 2;
                }
            }
        }
    }
    
    private void comprobarEmpate() {
        boolean empate = false;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaJuego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaJuego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton boton00;
    private javax.swing.JButton boton01;
    private javax.swing.JButton boton02;
    private javax.swing.JButton boton10;
    private javax.swing.JButton boton11;
    private javax.swing.JButton boton12;
    private javax.swing.JButton boton20;
    private javax.swing.JButton boton21;
    private javax.swing.JButton boton22;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
