/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicios.Ejercicio8;

/**
 *
 * @author marta
 */
public class VentanaCalculadora extends javax.swing.JFrame {

    private String valor_str1, valor_str2;
    private boolean boton_pulsado;
    private String accion;
    private String valor_mostrar, valor_operacion;
    /**
     * Creates new form Ejercicio8
     */
    public VentanaCalculadora() {
        
        valor_str1 = "";
        valor_str2 = "";
        valor_mostrar = "";
        valor_operacion = "";
        
        boton_pulsado = false;
        
        
        initComponents();
        etiqueta_muestra_operacion.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        b_limpiar = new javax.swing.JButton();
        b_raiz = new javax.swing.JButton();
        b_division = new javax.swing.JButton();
        b_borrar = new javax.swing.JButton();
        b_7 = new javax.swing.JButton();
        b_8 = new javax.swing.JButton();
        b_9 = new javax.swing.JButton();
        b_multiplicar = new javax.swing.JButton();
        b_4 = new javax.swing.JButton();
        b_5 = new javax.swing.JButton();
        b_6 = new javax.swing.JButton();
        b_restar = new javax.swing.JButton();
        b_1 = new javax.swing.JButton();
        b_2 = new javax.swing.JButton();
        b_3 = new javax.swing.JButton();
        b_sumar = new javax.swing.JButton();
        b_cambiar_signo = new javax.swing.JButton();
        b_0 = new javax.swing.JButton();
        b_punto = new javax.swing.JButton();
        b_igual = new javax.swing.JButton();
        etiqueta_valor = new javax.swing.JLabel();
        etiqueta_muestra_operacion = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        item_calculadora = new javax.swing.JMenuItem();
        item_cambiodivisa = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel3.setLayout(new java.awt.GridLayout(5, 4));

        b_limpiar.setBackground(new java.awt.Color(204, 204, 204));
        b_limpiar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_limpiar.setText("C");
        b_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_limpiarActionPerformed(evt);
            }
        });
        jPanel3.add(b_limpiar);

        b_raiz.setBackground(new java.awt.Color(204, 204, 204));
        b_raiz.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_raiz.setText("√");
        b_raiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_raizActionPerformed(evt);
            }
        });
        jPanel3.add(b_raiz);

        b_division.setBackground(new java.awt.Color(204, 204, 204));
        b_division.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_division.setText("÷");
        b_division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_divisionActionPerformed(evt);
            }
        });
        jPanel3.add(b_division);

        b_borrar.setBackground(new java.awt.Color(204, 204, 204));
        b_borrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_borrar.setIcon(new javax.swing.ImageIcon("C:\\Users\\marta.PILSA\\Downloads\\icons8-símbolo-vaciar-24.png")); // NOI18N
        b_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_borrarActionPerformed(evt);
            }
        });
        jPanel3.add(b_borrar);

        b_7.setBackground(new java.awt.Color(153, 153, 153));
        b_7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_7.setText("7");
        b_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_7ActionPerformed(evt);
            }
        });
        jPanel3.add(b_7);

        b_8.setBackground(new java.awt.Color(153, 153, 153));
        b_8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_8.setText("8");
        b_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_8ActionPerformed(evt);
            }
        });
        jPanel3.add(b_8);

        b_9.setBackground(new java.awt.Color(153, 153, 153));
        b_9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_9.setText("9");
        b_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_9ActionPerformed(evt);
            }
        });
        jPanel3.add(b_9);

        b_multiplicar.setBackground(new java.awt.Color(204, 204, 204));
        b_multiplicar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_multiplicar.setText("X");
        b_multiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_multiplicarActionPerformed(evt);
            }
        });
        jPanel3.add(b_multiplicar);

        b_4.setBackground(new java.awt.Color(153, 153, 153));
        b_4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_4.setText("4");
        b_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_4ActionPerformed(evt);
            }
        });
        jPanel3.add(b_4);

        b_5.setBackground(new java.awt.Color(153, 153, 153));
        b_5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_5.setText("5");
        b_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_5ActionPerformed(evt);
            }
        });
        jPanel3.add(b_5);

        b_6.setBackground(new java.awt.Color(153, 153, 153));
        b_6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_6.setText("6");
        b_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_6ActionPerformed(evt);
            }
        });
        jPanel3.add(b_6);

        b_restar.setBackground(new java.awt.Color(204, 204, 204));
        b_restar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_restar.setText("-");
        b_restar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_restarActionPerformed(evt);
            }
        });
        jPanel3.add(b_restar);

        b_1.setBackground(new java.awt.Color(153, 153, 153));
        b_1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_1.setText("1");
        b_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_1ActionPerformed(evt);
            }
        });
        jPanel3.add(b_1);

        b_2.setBackground(new java.awt.Color(153, 153, 153));
        b_2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_2.setText("2");
        b_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_2ActionPerformed(evt);
            }
        });
        jPanel3.add(b_2);

        b_3.setBackground(new java.awt.Color(153, 153, 153));
        b_3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_3.setText("3");
        b_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_3ActionPerformed(evt);
            }
        });
        jPanel3.add(b_3);

        b_sumar.setBackground(new java.awt.Color(204, 204, 204));
        b_sumar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_sumar.setText("+");
        b_sumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_sumarActionPerformed(evt);
            }
        });
        jPanel3.add(b_sumar);

        b_cambiar_signo.setBackground(new java.awt.Color(204, 204, 204));
        b_cambiar_signo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_cambiar_signo.setIcon(new javax.swing.ImageIcon("C:\\Users\\marta.PILSA\\Downloads\\icons8-más-menos-24.png")); // NOI18N
        b_cambiar_signo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cambiar_signoActionPerformed(evt);
            }
        });
        jPanel3.add(b_cambiar_signo);

        b_0.setBackground(new java.awt.Color(204, 204, 204));
        b_0.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_0.setText("0");
        b_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_0ActionPerformed(evt);
            }
        });
        jPanel3.add(b_0);

        b_punto.setBackground(new java.awt.Color(204, 204, 204));
        b_punto.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_punto.setText(".");
        b_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_puntoActionPerformed(evt);
            }
        });
        jPanel3.add(b_punto);

        b_igual.setBackground(new java.awt.Color(204, 204, 204));
        b_igual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_igual.setText("=");
        b_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_igualActionPerformed(evt);
            }
        });
        jPanel3.add(b_igual);

        etiqueta_valor.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        etiqueta_valor.setText("0");

        etiqueta_muestra_operacion.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(etiqueta_muestra_operacion)
                    .addComponent(etiqueta_valor))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(etiqueta_muestra_operacion)
                .addGap(18, 18, 18)
                .addComponent(etiqueta_valor)
                .addGap(26, 26, 26)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Usos");

        item_calculadora.setIcon(new javax.swing.ImageIcon("C:\\Users\\marta.PILSA\\Downloads\\seo-social-web-network-internet_92_icon-icons.com_61528.png")); // NOI18N
        item_calculadora.setText("Calculadora");
        jMenu1.add(item_calculadora);

        item_cambiodivisa.setIcon(new javax.swing.ImageIcon("C:\\Users\\marta.PILSA\\Downloads\\currency_exchange-48_46742 (1).png")); // NOI18N
        item_cambiodivisa.setText("Cambio de divisa");
        item_cambiodivisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_cambiodivisaActionPerformed(evt);
            }
        });
        jMenu1.add(item_cambiodivisa);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //MULTIPLICAR
    private void b_multiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_multiplicarActionPerformed
        // TODO add your handling code here:
        boton_pulsado = true;
        accion = "multiplicar";
        
        valor_mostrar = "";
        valor_operacion = valor_str1 + " x ";
        etiqueta_valor.setText("0");
        etiqueta_muestra_operacion.setText(valor_operacion);
    }//GEN-LAST:event_b_multiplicarActionPerformed

    private void b_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_1ActionPerformed
        // TODO add your handling code here:
        if (!boton_pulsado)
            valor_str1+="1";
        else 
            valor_str2+="1";
        
        valor_mostrar+="1";
        valor_operacion+="1";
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_1ActionPerformed

    // IGUAL
    private void b_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_igualActionPerformed
        // TODO add your handling code here:
        double valor1, valor2;
        double valor_total = 0;
        
        if (valor_str1.isBlank())
            valor1 = 0;
        else 
            valor1 = Double.parseDouble(valor_str1);
        
        if (valor_str2.isBlank())
            valor2 = 0;
        else 
            valor2 = Double.parseDouble(valor_str2);
        
        if (accion.equals("sumar"))
            valor_total = valor1 + valor2;
        else if (accion.equals("restar"))
            valor_total = valor1 - valor2;
        else if (accion.equals("multiplicar"))
            valor_total = valor1 * valor2;
        else if (accion.equals("dividir"))
            valor_total = valor1 / valor2;
        
        boton_pulsado = false;
        
        etiqueta_valor.setText(Double.toString(valor_total));
        etiqueta_muestra_operacion.setText(valor_operacion);
        valor_mostrar = "";
        valor_operacion = "";
        valor_str1="";
        valor_str2="";
    }//GEN-LAST:event_b_igualActionPerformed

    // SUMAR
    private void b_sumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_sumarActionPerformed
        // TODO add your handling code here:
        boton_pulsado = true;
        accion = "sumar";
        
        valor_mostrar = "";
        valor_operacion = valor_str1 +" + ";
        etiqueta_valor.setText("0");
        etiqueta_muestra_operacion.setText(valor_operacion);
        
    }//GEN-LAST:event_b_sumarActionPerformed

    // LIMPIAR
    private void b_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_limpiarActionPerformed
        // TODO add your handling code here:
        valor_mostrar = "";
        valor_operacion = "";
        etiqueta_muestra_operacion.setText(valor_operacion);
        etiqueta_valor.setText("0");
        boton_pulsado = false;
        valor_str1="";
        valor_str2="";
    }//GEN-LAST:event_b_limpiarActionPerformed

    private void b_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_2ActionPerformed
        // TODO add your handling code here:
        if (!boton_pulsado)
            valor_str1+="2";
        else 
            valor_str2+="2";
        
        valor_mostrar+="2";
        valor_operacion+="2";
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_2ActionPerformed

    private void b_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_3ActionPerformed
        // TODO add your handling code here:
        if (!boton_pulsado)
            valor_str1+="3";
        else 
            valor_str2+="3";
        
        valor_mostrar+="3";
        valor_operacion+="3";
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_3ActionPerformed

    private void b_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_4ActionPerformed
        // TODO add your handling code here:
        if (!boton_pulsado)
            valor_str1+="4";
        else 
            valor_str2+="4";
        
        valor_mostrar+="4";
        valor_operacion+="4";
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_4ActionPerformed

    private void b_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_5ActionPerformed
        // TODO add your handling code here:
        if (!boton_pulsado)
            valor_str1+="5";
        else 
            valor_str2+="5";
        
        valor_mostrar+="5";
        valor_operacion+="5";
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_5ActionPerformed

    private void b_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_6ActionPerformed
        // TODO add your handling code here:
        if (!boton_pulsado)
            valor_str1+="6";
        else 
            valor_str2+="6";
        
        valor_mostrar+="6";
        valor_operacion+="6";
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_6ActionPerformed

    private void b_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_7ActionPerformed
        // TODO add your handling code here:
        if (!boton_pulsado)
            valor_str1+="7";
        else 
            valor_str2+="7";
        
        valor_mostrar+="7";
        valor_operacion+="7";
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_7ActionPerformed

    private void b_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_8ActionPerformed
        // TODO add your handling code here:
        if (!boton_pulsado)
            valor_str1+="8";
        else 
            valor_str2+="8";
        
        valor_mostrar+="8";
        valor_operacion+="8";
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_8ActionPerformed

    private void b_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_9ActionPerformed
        // TODO add your handling code here:
        if (!boton_pulsado)
            valor_str1+="9";
        else 
            valor_str2+="9";
        
        valor_mostrar+="9";
        valor_operacion+="9";
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_9ActionPerformed

    private void b_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_0ActionPerformed
        // TODO add your handling code here:
        if (!boton_pulsado)
            valor_str1+="0";
        else 
            valor_str2+="0";
        
        valor_mostrar+="0";
        valor_operacion+="0";
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_0ActionPerformed

    // PUNTO
    
    private void b_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_puntoActionPerformed
        // TODO add your handling code here:
        if (!boton_pulsado)
            valor_str1+=".";
        else 
            valor_str2+=".";
        
        valor_mostrar+=".";
        valor_operacion = valor_str1 +".";
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_puntoActionPerformed

    // RESTAR
    private void b_restarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_restarActionPerformed
        // TODO add your handling code here:
        boton_pulsado = true;
        accion = "restar";
        
        valor_mostrar = "";
        valor_operacion = valor_str1 +" - ";
        etiqueta_valor.setText("0");
        etiqueta_muestra_operacion.setText(valor_operacion);
    }//GEN-LAST:event_b_restarActionPerformed

    // DIVIDIR
    private void b_divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_divisionActionPerformed
        // TODO add your handling code here:
        accion = "dividir";
        
        boton_pulsado = true;
        valor_mostrar = "";
        valor_operacion = valor_str1 +" ÷ ";
        etiqueta_valor.setText("0");
        etiqueta_muestra_operacion.setText(valor_operacion);
    }//GEN-LAST:event_b_divisionActionPerformed

    //RAIZ
    private void b_raizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_raizActionPerformed
        // TODO add your handling code here:
        double valor1 = 0 ;
        double total;
        
        if (valor_str1.isBlank())
            valor1 = 0;
        else 
            valor1 = Double.parseDouble(valor_str1);
        
        total = Math.sqrt(valor1);
                
        valor_mostrar = "";
        valor_operacion="sqrt(" + valor_str1 + ")";
        etiqueta_muestra_operacion.setText(valor_operacion);
        etiqueta_valor.setText(Double.toString(total));
        valor_operacion = "";
    }//GEN-LAST:event_b_raizActionPerformed

    //  BORRAR
    private void b_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_borrarActionPerformed
        // TODO add your handling code here:
        
        if (!boton_pulsado) {
            if (valor_str1.length()>1) {
                valor_str1 = valor_str1.substring(0, valor_str1.length()-1);
                valor_mostrar = valor_str1;
            }
            else {
                valor_str1 = "";
                valor_mostrar = "0";
            }
            
        }
        else {
            if (valor_str2.length()>1) {
                valor_str2 = valor_str2.substring(0, valor_str2.length()-1);
                valor_mostrar = valor_str2;
            }
            else {
                valor_str2 = "";
                valor_mostrar = "0";
            }
        }
        
        etiqueta_valor.setText(valor_mostrar);
    }//GEN-LAST:event_b_borrarActionPerformed

    private void b_cambiar_signoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cambiar_signoActionPerformed
        // TODO add your handling code here:
        double valor = Double.parseDouble(valor_str1);
        valor = valor*(-1);
        
        valor_str1 = Double.toString(valor);
        
        etiqueta_valor.setText(valor_str1);
    }//GEN-LAST:event_b_cambiar_signoActionPerformed

    private void item_cambiodivisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_cambiodivisaActionPerformed
        // TODO add your handling code here:
        new VentanaCambioDivisas().setVisible(true);
        dispose();
    }//GEN-LAST:event_item_cambiodivisaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaCalculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaCalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_0;
    private javax.swing.JButton b_1;
    private javax.swing.JButton b_2;
    private javax.swing.JButton b_3;
    private javax.swing.JButton b_4;
    private javax.swing.JButton b_5;
    private javax.swing.JButton b_6;
    private javax.swing.JButton b_7;
    private javax.swing.JButton b_8;
    private javax.swing.JButton b_9;
    private javax.swing.JButton b_borrar;
    private javax.swing.JButton b_cambiar_signo;
    private javax.swing.JButton b_division;
    private javax.swing.JButton b_igual;
    private javax.swing.JButton b_limpiar;
    private javax.swing.JButton b_multiplicar;
    private javax.swing.JButton b_punto;
    private javax.swing.JButton b_raiz;
    private javax.swing.JButton b_restar;
    private javax.swing.JButton b_sumar;
    private javax.swing.JLabel etiqueta_muestra_operacion;
    private javax.swing.JLabel etiqueta_valor;
    private javax.swing.JMenuItem item_calculadora;
    private javax.swing.JMenuItem item_cambiodivisa;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
