/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ahorcado;

import java.util.ArrayList;
import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author marta
 */
public class Ahorcado_ extends javax.swing.JFrame {

    ArrayList<ArrayList<String>> palabras;
    String pista, palabra;
    ArrayList<String> letras;
    int intentos;
    ArrayList<String> palabra_correcta;
    /**
     * Creates new form Ahorcado_
     */
    public Ahorcado_() {
        
        letras = new ArrayList<>();
        palabras = new ArrayList<ArrayList<String>>();
        intentos = 10;
        rellenarPalabras();
        cogerPistayPalabra();
        rellenarPalabraCorrecta();
        initComponents();
        etiqueta_palabra.setText("******");
        etiqueta_pista.setText(pista);
        
    }
    
    public void rellenarPalabraCorrecta() {
        palabra_correcta = new ArrayList<>();
        for (int i=0; i<6; i++ ){
            palabra_correcta.add("*");
        }
    }
    
    public void rellenarPalabras() {
       
        ArrayList<String> uno = new ArrayList<>();
        uno.add("Pais");
        uno.add("Espana");
        ArrayList<String> dos = new ArrayList<>();
        dos.add("Fruta");
        dos.add("Fresas");
        ArrayList<String> tres = new ArrayList<>();
        tres.add("Nombre");
        tres.add("Teresa");
        
        palabras.add(uno);
        palabras.add(dos);
        palabras.add(tres);
        
    }
    
    public void cogerPistayPalabra() {
        Random r = new Random();
	int index = r.nextInt(2+1);
        
        pista = palabras.get(index).get(0);
        palabra = palabras.get(index).get(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        etiqueta_pista = new javax.swing.JLabel();
        etiqueta_palabra = new javax.swing.JLabel();
        tf_letra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Pista:");

        etiqueta_palabra.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        etiqueta_palabra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tf_letra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_letraKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(etiqueta_palabra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(etiqueta_pista, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(tf_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(etiqueta_pista, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(etiqueta_palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(tf_letra, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void reiniciar() {
        pista = "";
        palabra = "";
        intentos = 10;
        
        palabra_correcta.clear();
        letras.clear();
        
        letras = new ArrayList<>();
        
        cogerPistayPalabra();
        rellenarPalabraCorrecta();
        
        tf_letra.setText("");
        etiqueta_palabra.setText("******");
        etiqueta_pista.setText(pista);
        
    }
    
    private void tf_letraKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_letraKeyReleased
        if (evt.getExtendedKeyCode() == 10){ // Tecla intro
            if (intentos != 0) { // Si no se han acabado los intentos.
                String letra = tf_letra.getText();
                if (letras.indexOf(letra) != -1) { // SI he repetido la letra.
                    JOptionPane.showMessageDialog(null, "Letra repetida. Dime otra.");
                    tf_letra.setText("");
                }
                else {
                    int index = palabra.indexOf(letra);
                    letras.add(letra); // Guardo la letra par ano repetirla
                    if (index == -1) { // La letra no está en la palabra
                        intentos--;
                        JOptionPane.showMessageDialog(null, "La letra no está. Quedan " + intentos + " intentos.");
                        tf_letra.setText("");
                    }
                    else { // La letra está en la palabra
                        for (int i=0; i<palabra.length(); i++) { // Cambio todos los asteriscos que coincidan por la letra
                            char ch = palabra.charAt(i);
                            String ch_s = Character.toString(ch);
                            if (ch_s.equals(letra)) {
                                palabra_correcta.set(i, letra);
                            }
                            
                        }
                        String p = "";
                        for (String s : palabra_correcta) {
                            p+=s; // Convierto el array en un string
                        }
                        etiqueta_palabra.setText(p);
                        
                        if (!p.contains("*")) { // Si en la palabra ya no hay asteriscos
                            JOptionPane.showMessageDialog(null, "Ha ganado.");
                            reiniciar();
                        }
                        else {
                            tf_letra.setText("");
                        }
                        
                    }
                }
            }
            else {
                JOptionPane.showMessageDialog(null, "Se han acabado los intentos. Ha perdido.");
                reiniciar();
            }
        }
    }//GEN-LAST:event_tf_letraKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ahorcado_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ahorcado_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ahorcado_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ahorcado_.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ahorcado_().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel etiqueta_palabra;
    private javax.swing.JLabel etiqueta_pista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_letra;
    // End of variables declaration//GEN-END:variables
}
